### PR TITLE
Kevtar/fix container scan

### PR DESCRIPTION
**Pull request by elveskevtar**

### CODE REVIEW

**Review by findyoky — CHANGES_REQUESTED** [review]
For the Docker daemon status check: 1) Specify the daemon configuration file location since it is more secure method as it verifies the intended configuration than just the running process.  The daemon may started with diff configuration.  2) The suggested logging level is "Info".  Why using custom log level flag is better than "Info"?  3) What are the custom log levels are there?

**Comment by elveskevtar** [comment]
> For the Docker daemon status check: 1) Specify the daemon configuration file location since it is more secure method as it verifies the intended configuration than just the running process. The daemon may started with diff configuration. 2) The suggested logging level is "Info". Why using custom log level flag is better than "Info"? 3) What are the custom log levels are there?

The problem with this one is that it seems the daemon file does not exist at that location or the runner does not have permission to access it. I was trying to figure out where it was but could not find it. I figured we could check the existing process and see if custom log levels are set. I mainly just want it to stop failing on each commit. Do you happen to know where the daemon file is located for the Github runner?

**Comment by findyoky** [comment]
Created PR#80 to display the location of the docker daemon location.  Please approve it when you get a chance.  Thx!

**Comment by elveskevtar** [comment]
> Created PR#80 to display the location of the docker daemon location. Please approve it when you get a chance. Thx!
> 
> Ran "which dockerd" and returned location -> /usr/bin/dockerd

Approved. What should I do now?

**Comment by findyoky** [comment]
> > Created PR#80 to display the location of the docker daemon location. Please approve it when you get a chance. Thx!
> > Ran "which dockerd" and returned location -> /usr/bin/dockerd
> 
> Approved. What should I do now?

**Pull request closed without merging**
